### ISSUE TITLE
Wrong doctype reference in index.html

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/nisha#1]
presently
<code>DOCTYPE kjqwrlhwgva</code>

expected
<code>DOCTYPE html</code>

File to chnage can be found <a href="https://github.com/himanshu007-creator/nisha/blob/main/extension/index.html">here</a>

**Comment by colonealcortez** [comment]
hi @himanshu007-creator . i am a participant @gssoc, kindly assign me this issue.

**Comment by himanshu007-creator** [comment]
ye kam hogaya
